# Generated by Django 4.2.21 on 2025-05-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'users', 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
